apiVersion: v1
kind: ConfigMap
metadata:
  name: order-api-configmap
data:
  ConnectionStrings__DefaultConnection: "Server=mysql;Port=3306;Database=ContactsDb;User=grupo10;Password=yourpassword;"
  SecretJWT: "MBAFIAPabcdefghijlmnopqrstuvxz123456789"
  Server: "rabbitmq-clusterip"
  Port: "5672"