apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api-deployment
  annotations:
    autor: Marcelo Cedro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
        - name: order-api
          image: maxcedro/hackatoonorder:latest
          ports:
            - containerPort: 8087
          resources:
            limits:
              cpu: "0.5"
              memory: 512Mi
            requests:
              cpu: "0.2"
              memory: 256Mi
          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8087"

            # Connection String
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: order-api-secrets
                  key: DefaultConnection

            # ElasticSearch
            - name: ElasticSettings__ApiKey
              valueFrom:
                secretKeyRef:
                  name: order-api-secrets
                  key: ApiKey
            - name: ElasticSettings__CloudId
              valueFrom:
                secretKeyRef:
                  name: order-api-secrets
                  key: CloudId

            # JWT
            - name: SecretJWT
              valueFrom:
                secretKeyRef:
                  name: order-api-secrets
                  key: SecretJWT

            # MassTransit / RabbitMQ
            - name: MassTransit__User
              valueFrom:
                secretKeyRef:
                  name: order-api-secrets
                  key: User
            - name: MassTransit__Password
              valueFrom:
                secretKeyRef:
                  name: order-api-secrets
                  key: Password
            - name: MassTransit__Server
              valueFrom:
                configMapKeyRef:
                  name: order-api-configmap
                  key: MassTransit__Server
            - name: MassTransit__Port
              valueFrom:
                configMapKeyRef:
                  name: order-api-configmap
                  key: MassTransit__Port

            # MassTransit QueueList
            - name: MassTransit__QueueList__InsertQueue
              valueFrom:
                configMapKeyRef:
                  name: order-api-configmap
                  key: MassTransit__QueueList__InsertQueue
            - name: MassTransit__QueueList__UpdateQueue
              valueFrom:
                configMapKeyRef:
                  name: order-api-configmap
                  key: MassTransit__QueueList__UpdateQueue
            - name: MassTransit__QueueList__DeleteQueue
              valueFrom:
                configMapKeyRef:
                  name: order-api-configmap
                  key: MassTransit__QueueList__DeleteQueue
