apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kubernetes-api-hpa
  namespace: default  # Substitua pelo seu namespace, se necessário
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-api-deployment  # Nome do seu deployment
  minReplicas: 1  # Número mínimo de réplicas
  maxReplicas: 10  # Número máximo de réplicas
  metrics:
    - type: Resource
      resource:
        name: cpu  # Métrica de CPU
        target:
          type: Utilization
          averageUtilization: 50  # O HPA tenta manter a utilização da CPU em 50%