# Service ClusterIP: Acesso interno (dentro do cluster)
apiVersion: v1
kind: Service
metadata:
  name: order-api-clusterip
spec:
  selector:
    app: order-api        # <-- corrigido para casar com o Deployment
  ports:
    - protocol: TCP
      port: 80            # Porta que outros serviços dentro do cluster usarão
      targetPort: 8087    # Porta do container da aplicação
  type: ClusterIP
---
# Service NodePort: Acesso externo básico (com IP do nó)
apiVersion: v1
kind: Service
metadata:
  name: order-api-nodeport
spec:
  selector:
    app: order-api        # <-- corrigido
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8087
      nodePort: 30080
  type: NodePort
---
# Service LoadBalancer: Acesso externo gerenciado (em nuvem)
apiVersion: v1
kind: Service
metadata:
  name: order-api-lb
spec:
  selector:
    app: order-api        # <-- corrigido
  ports:
    - protocol: TCP
      port: 5087          # Porta exposta externamente via LoadBalancer
      targetPort: 8087
  type: LoadBalancer
